src/AspNetCore/MyAspNetCoreApp/Models/ErrorViewModel.cs
using System;

namespace MyAspNetCoreApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/AspNetCore/MyAspNetCoreApp/Models/PodcastViewModel.cs
namespace MyAspNetCoreApp.Models
{
    public class PodcastViewModel
    {
        private int views;

        public string? Name { get; set; }

        public int Downloads { get; set; }

        public int Streams { get; set; }

        public int Views
        {
            get => Downloads + Streams;
            private set => views = value;
        }

        public DateTime Date { get; set; }

        public int Reach { get; set; }

        public string? Device { get; set; }

        public string? PlatformName { get; set; }
    }
}

src/AspNetCore/MyAspNetCoreApp/Controllers/DashboardController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using MyAspNetCoreApp.Models;

namespace MyAspNetCoreApp.Controllers
{
    public class DashboardController : Controller
    {
        private readonly List<string> firstNames = new() { "Nancy", "Andrew", "Janet", "Margaret", "Steven", "Michael", "Robert", "Laura", "Anne", "Nige" };
        private readonly List<string> lastNames = new() { "Davolio", "Fuller", "Leverling", "Peacock", "Buchanan", "Suyama", "King", "Callahan", "Dodsworth", "White" };
        private readonly List<string> platforms = new() { "Apple Podcasts", "Spotify", "Other", "Overcast", "Anchor", "Stitcher" };
        private readonly List<string> devices = new() { "iOS", "Android", "Other", "Web" };

        public static Random Random = new();

        public static List<PodcastViewModel> Podcasts = new();

        public ActionResult Podcasts_Read([DataSourceRequest] DataSourceRequest request)
        {
            var result = GetPodcasts().ToDataSourceResult(request);
            ViewData["test"] = result.AggregateResults;
            return Json(result);
        }

        public ActionResult Downloads_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(GetPodcasts());
        }

        public ActionResult Devices_Read([DataSourceRequest] DataSourceRequest request)
        {
            var deviceViews = GetPodcasts()
                .GroupBy(x => x.Device)
                .Select(x => new
                {
                    Device = x.Key,
                    Views = x.Sum(v => v.Views)
                });

            return Json(deviceViews);
        }

        public ActionResult Platforms_Read([DataSourceRequest] DataSourceRequest request)
        {
            var platformViews = GetPodcasts()
                .GroupBy(x => x.PlatformName)
                .Select(x => new
                {
                    PlatformName = x.Key,
                    Views = x.Sum(v => v.Views)
                });

            return Json(platformViews);
        }
        private IEnumerable<PodcastViewModel> GetPodcasts()
        {
            if (Podcasts.Count == 0)
            {
                Podcasts = Enumerable.Range(1, 50).Select(x => new PodcastViewModel()
                {
                    Name = $"Episode #{Random.Next(0, 200)} with guest {firstNames[Random.Next(0, firstNames.Count)]} {lastNames[Random.Next(0, lastNames.Count)]}",
                    Streams = Random.Next(0, 18000),
                    Downloads = Random.Next(0, 15000),
                    PlatformName = platforms[Random.Next(0, platforms.Count)],
                    Device = devices[Random.Next(0, devices.Count)],
                    Date = DateTime.Now.AddDays(-x),
                    Reach = x * Random.Next(0, 1000),
                }).ToList();
            }

            return Podcasts;
        }
    }
}

src/AspNetCore/MyAspNetCoreApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyAspNetCoreApp.Models;
using System.Diagnostics;

namespace MyAspNetCoreApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ReportViewer()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/AspNetCore/MyAspNetCoreApp/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;
using Telerik.Reporting.Services;
using Telerik.Reporting.Services.AspNetCore;

namespace MyAspNetCoreApp.Controllers;

[Route("api/reports")]
[ApiController]
public class ReportsController : ReportsControllerBase
{
    public ReportsController(IReportServiceConfiguration reportServiceConfiguration)
        : base(reportServiceConfiguration)
    {
    }

    protected override HttpStatusCode SendMailMessage(MailMessage mailMessage)
    {
        throw new System.NotImplementedException("This method should be implemented in order to send mail messages");

        // using (var smtpClient = new SmtpClient("smtp01.mycompany.com", 25))
        // {
        //     smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
        //     smtpClient.EnableSsl = false;
        //     smtpClient.Send(mailMessage);
        // }
        // return HttpStatusCode.OK;
    }
}

src/AspNetCore/MyAspNetCoreApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    .k-footer-template {
        display: none;
    }

    .k-card-header {
        flex: 0 0 auto;
    }

    .k-card-body {
        overflow: hidden;
    }

    .k-chart, .k-grid {
        height: 100%;
    }
</style>

<!-- container text templates -->
<script id="total-streams-template" type="text/x-kendo-template">
    <h2 id="total-streams"></h2>
</script>
<script id="total-downloads-template" type="text/x-kendo-template">
    <h2 id="total-downloads"></h2>
</script>
<script id="reach-template" type="text/x-kendo-template">
    <h2 id="total-reach"></h2>
</script>
<script id="revenue-template" type="text/x-kendo-template">
    <h2 id="total-revenue"></h2>
</script>

<kendo-datasource name="dateChartDataSource" type="DataSourceTagHelperType.Custom">
    <transport>
        <read url="@Url.Action("Downloads_Read", "Dashboard")" />
    </transport>
</kendo-datasource>

<!-- container chart templates -->
<script id="downloads-chart-template" type="text/html">
    <kendo-chart name="downloads" datasource-id="dateChartDataSource" is-in-client-template="true">
        <chart-legend visible="false"></chart-legend>
        <value-axis>
            <value-axis-item min="2000" max="16000">
                <labels step="4"></labels>
            </value-axis-item>
        </value-axis>
        <category-axis>
            <category-axis-item type="ChartCategoryAxisType.Date" base-unit="ChartAxisBaseUnit.Fit">
                <labels format="{0:d MMM}">
                    <chart-category-axis-labels-rotation angle="300" />
                </labels>
                <major-grid-lines visible="false" />
                <major-ticks visible="false" />
            </category-axis-item>
        </category-axis>
        <series>
            <series-item category-field="Date" field="Downloads" type="ChartSeriesType.Line">
            </series-item>
        </series>
    </kendo-chart>
</script>

<!-- To configure the chart theme to match the application theme use the theme setting https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart/configuration/theme -->
<script id="performance-chart-template" type="text/html">
    <kendo-chart name="performance" datasource-id="dateChartDataSource" is-in-client-template="true" auto-bind="false">
        <chart-legend visible="false"></chart-legend>
        <value-axis>
            <value-axis-item min="4000" max="30000">
                <labels step="3"></labels>
            </value-axis-item>
        </value-axis>
        <category-axis>
            <category-axis-item type="ChartCategoryAxisType.Date" base-unit="ChartAxisBaseUnit.Fit">
                <labels format="{0:d MMM}">
                    <chart-category-axis-labels-rotation angle="300" />
                </labels>
                <major-grid-lines visible="false" />
                <major-ticks visible="false" />
            </category-axis-item>
        </category-axis>
        <series>
            <series-item category-field="Date" field="Views" type="ChartSeriesType.Column">
            </series-item>
        </series>
    </kendo-chart>
</script>

<script id="apps-chart-template" type="text/html">
    <kendo-chart name="devices" is-in-client-template="true">
        <series>
            <series-item type="ChartSeriesType.Donut" auto-fit="true" category-field="Device" field="Views">
                <labels visible="true"
                        template="\\#=category\\#"
                        background="transparent"
                        position="ChartSeriesLabelsPosition.OutsideEnd">
                </labels>
            </series-item>
        </series>
        <chart-legend visible="false"></chart-legend>
        <datasource>
            <transport>
                <read url="@Url.Action("Devices_Read", "Dashboard")" />
            </transport>
        </datasource>
    </kendo-chart>
</script>

<script id="platforms-chart-template" type="text/html">
    <kendo-chart name="platforms" is-in-client-template="true">
        <series>
            <series-item type="ChartSeriesType.Donut" auto-fit="true" category-field="PlatformName" field="Views">
                <labels visible="true"
                        template="\\#=category\\#"
                        background="transparent"
                        position="ChartSeriesLabelsPosition.OutsideEnd">
                </labels>
            </series-item>
        </series>
        <chart-legend visible="false"></chart-legend>
        <datasource>
            <transport>
                <read url="@Url.Action("Platforms_Read", "Dashboard")" />
            </transport>
        </datasource>
    </kendo-chart>
</script>

<!-- container grid template -->
<script id="grid-template" type="text/html">
    <kendo-grid name="grid" on-data-bound="populateTotals" is-in-client-template="true">
        <sortable enabled="true" />
        <columns>
            <column field="Name" width="320" title="Podcast Episode"></column>
            <column field="Streams" width="150"></column>
            <column field="Downloads" width="250"></column>
        </columns>
        <datasource type="DataSourceTagHelperType.Ajax" page-size="5">
            <transport>
                <read url="@Url.Action("Podcasts_Read", "Dashboard")" />
            </transport>
            <sorts>
                <sort field="Streams" direction="desc" />
            </sorts>
            <aggregates>
                <aggregate field="Downloads" aggregate="sum" />
                <aggregate field="Streams" aggregate="sum" />
                <aggregate field="Reach" aggregate="sum" />
                <aggregate field="Views" aggregate="sum" />
            </aggregates>
        </datasource>
    </kendo-grid>
</script>

<div class="d-flex justify-content-center">
    <kendo-tilelayout name="tilelayout" columns="4" resizable="true" reorderable="true" columns-width="350px" rows-height="145px" on-resize="onTileResize">
        <containers>
            <container body-template-id="total-streams-template" col-span="1" row-span="1">
                <container-header text="Total Streams" />
            </container>
            <container body-template-id="total-downloads-template" col-span="1" row-span="1">
                <container-header text="Total Downloads" />
            </container>
            <container body-template-id="reach-template" col-span="1" row-span="1">
                <container-header text="Reach" />
            </container>
            <container body-template-id="revenue-template" col-span="1" row-span="1">
                <container-header text="Revenue" />
            </container>
            <container body-template-id="downloads-chart-template" col-span="2" row-span="3">
                <container-header text="Weekly Recap-Downloads" />
            </container>
            <container body-template-id="performance-chart-template" col-span="2" row-span="3">
                <container-header text="Performance Trend" />
            </container>
            <container body-template-id="grid-template" col-span="4" row-span="2">
                <container-header text="Top 5 Episodes" />
            </container>
            <container body-template-id="apps-chart-template" col-span="2" row-span="2">
                <container-header text="Listening platforms-Apps" />
            </container>
            <container body-template-id="platforms-chart-template" col-span="2" row-span="2">
                <container-header text="Listening platforms-Devices" />
            </container>
        </containers>
    </kendo-tilelayout>

    <script>
        function populateTotals(e) {
            // we are using the aggregates of the grid to populate our totals
            var aggregates = e.sender.dataSource.aggregates();

            $("#total-streams").html(kendo.toString(aggregates.Streams.sum, "n0"));
            $("#total-downloads").html(kendo.toString(aggregates.Downloads.sum, "n0"));
            $("#total-reach").html(kendo.toString(aggregates.Reach.sum, "n0"));
            $("#total-revenue").html(kendo.toString(aggregates.Views.sum / 100, "c0"));
        }

        function onTileResize(e) {
            // for widgets that do not auto resize https://docs.telerik.com/kendo-ui/styles-and-layout/using-kendo-in-responsive-web-pages
            kendo.resize(e.container, true);
        }
    </script>
</div>

src/AspNetCore/MyAspNetCoreApp/Views/Home/ReportViewer.cshtml
<style type="text/css">
    #reportViewer1 {
        position: absolute;
        left: 5px;
        right: 5px;
        top: 50px;
        bottom: 5px;
        overflow: hidden;
        font-family: Verdana, Arial;
    }
</style>

<div id="reportViewer1">
    loading report viewer...
</div>

<script>
    $(document).ready(function () {
        $("#reportViewer1").telerik_ReportViewer({
            serviceUrl: "/api/reports/",
            reportSource: {
                report: "Barcodes Report.trdp"
            },
            viewMode: telerikReportViewer.ViewModes.INTERACTIVE,
            scaleMode: telerikReportViewer.ScaleModes.SPECIFIC,
            scale: 1.0,
            enableAccessibility: false,
            sendEmail: { enabled: false }
        });
    });
</script>

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/Boolean.cshtml
@model bool?

@(Html.Kendo().CheckBoxFor(m => m).HtmlAttributes(new { title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")}))

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/Country.cshtml
@model string

@(Html.Kendo().DropDownListFor(m => m)
            .DataValueField("CountryNameShort")
            .DataTextField("CountryNameLong")
            .HtmlAttributes(new { data_bind = "value: Country" })
            .Template(@"<div class='dropdown-country-wrap'><img src='" + @Url.Content("~/content/web/country-flags/#:data.CountryNameShort#.png") + "' alt='#: data.CountryNameLong#' title='#: data.CountryNameLong#' width='20' /><span>#: data.CountryNameLong #</span></div>")
            .BindTo((System.Collections.IEnumerable)ViewData["countries"])
            .AutoWidth(true)
)

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/Currency.cshtml
@model decimal?

@(Html.Kendo().CurrencyTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%", title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")})
      .Min(0)
)

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime?

@(Html.Kendo().DatePickerFor(m => m).HtmlAttributes(new { title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")}))

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?

@(Html.Kendo().DateTimePickerFor(m => m).HtmlAttributes(new { title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")}))

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/Email.cshtml
@model object 

<span class="k-input k-textbox k-input-solid k-input-md k-rounded-md">
    @Html.TextBoxFor(model => model, new { @class = "k-input-inner"})
</span>

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/EmailAddress.cshtml
@model object 

<span class="k-input k-textbox k-input-solid k-input-md k-rounded-md">
    @Html.TextBoxFor(model => model, new { @class = "k-input-inner", type = "email" })
</span>

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/GridForeignKey.cshtml
@model object

@(
 Html.Kendo().DropDownListFor(m => m)
        .BindTo((SelectList)ViewData[ViewData.TemplateInfo.GetFullHtmlFieldName("") + "_Data"])
        .HtmlAttributes(new { title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")})
)

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/Integer.cshtml
@model int?

@(Html.Kendo().IntegerTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%", title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")})
      .Min(int.MinValue)
      .Max(int.MaxValue)
)

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/Number.cshtml
@model double?

@(Html.Kendo().NumericTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
      .HtmlAttributes(new { title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")})
)

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/Password.cshtml
@model object 

<span class="k-input k-textbox k-input-solid k-input-md k-rounded-md">
    @Html.TextBoxFor(model => model, new { @class = "k-input-inner", type = "password" })
</span>

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/String.cshtml
@model object 

@Html.Kendo().TextBoxFor(model => model)

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/Time.cshtml
@model DateTime?

@(Html.Kendo().TimePickerFor(m => m).HtmlAttributes(new {title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")}))

src/AspNetCore/MyAspNetCoreApp/Views/Shared/EditorTemplates/Url.cshtml
@model object 

<span class="k-input k-textbox k-input-solid k-input-md k-rounded-md">
    @Html.TextBoxFor(model => model, new { @class = "k-input-inner", type = "url" })
</span>

src/AspNetCore/MyAspNetCoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyAspNetCoreApp</title>

    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
    <!-- Kendo resources -->
    <link href="https://cdn.kendostatic.com/themes/8.0.1/default/default-ocean-blue.css" rel="stylesheet" type="text/css" />
    
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    @* <script src="https://cdn.kendostatic.com/2024.2.514/js/jszip.min.js"></script> *@
    <script src="https://cdn.kendostatic.com/2024.2.514/js/kendo.all.min.js"></script>
    <script src="https://cdn.kendostatic.com/2024.2.514/js/kendo.aspnetmvc.min.js"></script>
    
    <script src="/js/kendo-ui-license.js"></script>
    
    <!-- Reporting resources -->
    <script src="/api/reports/resources/js/telerikReportViewer"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="ReportViewer">Report Viewer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020-2024 Lance McCarthy, Progress Software - MyAspNetCoreApp
        </div>
    </footer>

    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>